const icons = {
	ARCHIVED: require("../resources/archived.png"),
	BANNED: require("../resources/banned.png"),
	BARS: require("../resources/bars.png"),
	BELL: require("../resources/notification_settings.png"),
	BOLD: require("../resources/bold.png"),
	CARET_UP_SOLID: require("../resources/caret_up_solid.png"),
	CARET_DOWN_SOLID: require("../resources/caret_down_solid.png"),
	CHECKMARK2: require("../resources/checkmark_alt.png"),
	CHECKMARK: require("../resources/checkmark.png"),
	CHECKMARK_CIRCLE_SOLID: require("../resources/checkmark_circle_solid.png"),
	COG: require("../resources/settings.png"),
	CROSS: require("../resources/close.png"),
	CROSS_CIRCLE_SOLID: require("../resources/close_circle.png"),
	DOTS: require("../resources/dots.png"),
	ERROR: require("../resources/error.png"),
	FIRE: require("../resources/hot.png"),
	HEART: require("../resources/comment_like.png"),
	HEART_SOLID: require("../resources/heart_solid.png"),
	IMAGE: require("../resources/image.png"),
	INFO_SOLID: require("../resources/info_filled.png"),
	ITALIC: require("../resources/italic.png"),
	LINK: require("../resources/link.png"),
	LIST_ORDERED: require("../resources/list_ordered.png"),
	LIST_UNORDERED: require("../resources/list_unordered.png"),
	LOCKED: require("../resources/locked.png"),
	LOGIN: require("../resources/login.png"),
	LOGIN_SOLID: require("../resources/login_active.png"),
	MENTION: require("../resources/mention.png"),
	MULTI_BROWSE: require("../resources/multi_browse.png"),
	MULTI_BROWSE_SOLID: require("../resources/multi_browse_active.png"),
	MULTI_MINE: require("../resources/multi_mine.png"),
	MULTI_MINE_SOLID: require("../resources/multi_mine_active.png"),
	MULTI_SETTINGS: require("../resources/multi_settings.png"),
	MULTI_SETTINGS_SOLID: require("../resources/multi_settings_active.png"),
	OFFLINE: require("../resources/offline.png"),
	PENCIL: require("../resources/pencil.png"),
	PINNED: require("../resources/pinned.png"),
	PLUS: require("../resources/plus.png"),
	PLUS_CIRCLE: require("../resources/plus_outline.png"),
	QUOTE: require("../resources/comment_quote.png"),
	QUOTE_SOLID: require("../resources/comment_quote_solid.png"),
	REPLY: require("../resources/reply.png"),
	SEARCH: require("../resources/search.png"),
	SIGN_OUT: require("../resources/signout.png"),
	STAR_SOLID: require("../resources/star_solid.png"),
	TAG: require("../resources/tag.png"),
	TAG_SOLID: require("../resources/tag_solid.png"),
	TRASH: require("../resources/trash.png"),
	UNDERLINE: require("../resources/underline.png"),
	USER_DOCUMENT: require("../resources/edit_profile.png"),
	POLL: require("../resources/poll.png"),
	VIEW: require("../resources/view.png"),
	VOTE_UP: require("../resources/vote_up.png"),
	VOTE_UP_SOLID: require("../resources/vote_up_solid.png"),
	VOTE_DOWN: require("../resources/vote_down.png"),
	VOTE_DOWN_SOLID: require("../resources/vote_down_solid.png")
};

export const illustrations = {
	NOTIFICATIONS: require("../resources/illustration_notifications.png"),
	LIST: require("../resources/illustration_list.svg"),
	EMPTY: require("../resources/illustration_empty.png"),
	COMMUNITY: require("../resources/illustration_community.png"),
	SEARCH_LIST: require("../resources/illustration_search.png")
};

export default icons;
