const icons = {
	ARCHIVED: require("../resources/archived.png"),
	BELL: require("../resources/notification_settings.png"),
	CARET_UP_SOLID: require("../resources/caret_up_solid.png"),
	CARET_DOWN_SOLID: require("../resources/caret_down_solid.png"),
	CHECKMARK2: require("../resources/checkmark_alt.png"),
	CHECKMARK: require("../resources/checkmark.png"),
	CHECKMARK_CIRCLE_SOLID: require("../resources/checkmark_circle_solid.png"),
	COG: require("../resources/settings.png"),
	CROSS: require("../resources/close.png"),
	FIRE: require("../resources/hot.png"),
	HEART: require('../resources/comment_like.png'),
	HEART_SOLID: require('../resources/heart_solid.png'),
	LOCKED: require("../resources/locked.png"),
	PENCIL: require("../resources/pencil.png"),
	PINNED: require("../resources/pinned.png"),
	PLUS_CIRCLE: require("../resources/plus.png"),
	QUOTE: require('../resources/comment_quote.png'),
	QUOTE_SOLID: require('../resources/comment_quote_solid.png'),
	REPLY: require('../resources/reply.png'),
	SEARCH: require("../resources/search.png"),
	SIGN_OUT: require("../resources/signout.png"),
	STAR_SOLID: require("../resources/star_solid.png"),
	TAG: require("../resources/tag.png"),
	TAG_SOLID: require("../resources/tag_solid.png"),
	TRASH: require("../resources/trash.png"),
	USER_DOCUMENT: require("../resources/edit_profile.png"),
	POLL: require("../resources/poll.png"),
	VIEW: require("../resources/view.png"),
	VOTE_UP: require("../resources/vote_up.png"),
	VOTE_UP_SOLID: require("../resources/vote_up_solid.png"),
	VOTE_DOWN: require("../resources/vote_down.png"),
	VOTE_DOWN_SOLID: require("../resources/vote_down_solid.png"),
};

export default icons;