export default [
	//------------------------------------
	// Basic
	"replies",
	"topics",
	"posts",
	"quote",
	"post_options",
	"end_of_forum",
	"cancel",
	"post_action",
	"save",
	"confirm",
	"add",
	"report",
	"show",
	"hide",
	"replace",
	"load_earlier",
	"write_reply",
	"unread_posts",
	"your_profile",
	"settings",
	"sign_out",
	"notification_settings",
	"disabled_notification",
	"legal_notices",
	"edit_profile",
	"offline",
	"home",
	"browse",
	"our_picks",
	"new_content",
	"active_users",
	"popular_contributors",
	"x_more",
	"no_users_online",
	"x_guests_online",
	"activity_replied",
	"activity_commented",
	"activity_reviewed",
	"activity_posted_item",
	"activity_generic",
	"login_prompt",
	"login_register_prompt",
	"login_prompt_comment",
	"login_register_prompt_comment",
	"register",
	"sign_in",
	"home_view_error",
	"topic_view_error",
	"no_topics",
	"forum_requires_password",
	"enter_password",
	"password",
	"go",
	"error",
	"error_remove_reaction",
	"error_reacting",
	"error_following",
	"error_unfollowing",
	"ok",
	"cant_show_reactions",
	"editor_quote_line_with_time",
	"editor_quote_line",
	"ignoring_user",
	"pagination",
	"insert_into_post",
	"delete_image",
	"cancel_upload",
	"attachment_options",
	"no_matching_members",
	"rep",
	"no_rep_this_week",
	"list_two",
	"list_three",

	//------------------------------------
	// Sharing
	"share",
	"error_sharing_content",
	"share_x",
	"share_x_on_x_at_x",

	//------------------------------------
	// Profiles
	"followed_member",
	"unfollowed_member",
	"profile_content_count",
	"profile_reputation",
	"profile_followers",
	"profile_overview",
	"profile_content",
	"basic_information",
	"joined",
	"email_address",
	"end_of_profile_content",

	//------------------------------------
	// Login
	"username",
	"password",
	"forgot_password",
	"sign_in_anon",
	"sign_in_with_social",

	//------------------------------------
	// Search
	"search_site",
	"loading",
	"no_recent_searches",
	"error_searching",
	"no_results",
	"no_results_in_x",
	"see_all",
	"name_replied",
	"item_in_container",
	"overview",
	"top_content",
	"top_members",
	"recent_searches",
	"content",

	//------------------------------------
	// Topics
	"create_new_topic",
	"topics_title",
	"subforums_title",
	"no_forum",
	"no_topic",
	"incorrect_forum_password",
	"no_post",
	"invalid_topic",
	"not_question",
	"cannot_vote",
	"error_voting_question",
	"replace_best_answer_title",
	"replace_best_answer_text",
	"question_asked_by",
	"this_is_best_answer",

	//------------------------------------
	// Polls
	"votes",
	"votes_nonum",
	"poll_closed",
	"poll_closes_date",
	"poll_view",
	"poll_view_results",
	"poll_view_and_vote",
	"poll_you_voted",
	"poll_prefix",
	"poll_question_number",
	"poll_multiple_choice",
	"poll_view_confirm",
	"poll_no_permission",

	//------------------------------------
	// Tags
	"tags_min_max",
	"tags_min",
	"tags_max",
	"tags_len_min_max",
	"tags_len_min",
	"tags_len_max",
	"manage_tags",
	"enter_tag",
	"tags",
	"tag_suggestions",

	//------------------------------------
	// Notification list
	"no_more_notifications",
	"notifications_unread",
	"notifications_read",
	"no_notifications",

	//------------------------------------
	// Streams
	"switch_stream",
	"past_hour",
	"yesterday",
	"today",
	"last_week",
	"earlier",

	//------------------------------------
	// Follows
	"x_follow_this",
	"follow_immediate",
	"follow_weekly",
	"follow_daily",
	"follow_none",
	"follow_anon",
	"follow_freq",
	"follow_privacy",
	"follow",
	"follow_save",
	"unfollow",
	"error_select_follow_option",

	//------------------------------------
	// Reports
	"reporting_x_in_x",
	"revoke_report_x_in_x",
	"reporting_x",
	"revoke_report_x",
	"error_must_select_report_reason",
	"error_already_reported",
	"error_report_failed",
	"error_cannot_report",
	"error_revoke_failed",
	"thanks_for_report",
	"revoke_success",
	"sending_report",
	"send_report",
	"sending_revoke",
	"send_revoke",
	"choose_reason",
	"report_reason",
	"additional_report_info",
	"no_additional_info",
	"report_info_placeholder",
	"report_unknown",

	//------------------------------------
	// Notification settings
	"notification_group_core",
	"notifications__club_invitation",
	"notifications__club_response",
	"notifications__club_request",
	"notifications__club_join",
	"notifications__unapproved_club",
	"notifications__new_content",
	"notifications__new_comment",
	"notifications__new_review",
	"notifications__follower_content",
	"notifications__quote",
	"notifications__mention",
	"notifications__embed",
	"notifications__new_likes_rep",
	"notifications__new_likes_like",
	"notifications__warning_mods",
	"notifications__report_center",
	"notifications__automatic_moderation",
	"notifications__unapproved_content",
	"notifications__new_private_message",
	"notifications__private_message_added",
	"notifications__member_follow",
	"notifications__profile_comment",
	"notifications__profile_reply",
	"notifications__new_status",
	"notification_type_push",
	"notification_type_email",
	"notification_type_inline",
	"notification_type_none",

	//------------------------------------
	// Legal
	"legal_terms",
	"legal_guidelines",
	"legal_privacy",
	"third_party_licenses"
];
